### ISSUE TITLE
BUG - @sap-ux/preview-middleware fails when serving opa5/qunit test files executed via karma

### ISSUE THREAD

**Issue by heimwege** [SAP/open-ux-tools#1815]
Hey guys,

the preview-middleware can [serve qunit and opa5 test files](https://github.com/SAP/open-ux-tools/pull/1726). This works pretty well using e.g. [ui5-test-runner](https://github.com/ArnaudBuchholz/ui5-test-runner). If you use [karma](https://karma-runner.github.io/) as test runner you get the following error:

```
[info] graph:helpers:ui5Framework: Using SAPUI5 version: 1.120.9
debug preview-middleware Config: {"flp":{"path":"/localService/index.html","apps":[]},"test":[{"framework":"Qunit"},{"framework":"OPA5"}]}
debug preview-middleware Add route for /test/unitTests.qunit.html
debug preview-middleware Add route for /test/unitTests.qunit.js
debug preview-middleware Add route for /test/opaTests.qunit.html
debug preview-middleware Add route for /test/opaTests.qunit.js
info preview-middleware Initialized for app the.id.of.the.app
debug preview-middleware Configured apps: {"app-preview":{"title":"{{appTitle}}","description":"{{appDescription}}","additionalInformation":"SAPUI5.Component=the.id.of.the.app","applicationType":"URL","url":"..","applicationDependencies":{"manifest":true}}}
05 04 2024 09:22:18.488:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
05 04 2024 09:22:18.491:INFO [launcher]: Launching browsers ChromeMaximized with concurrency unlimited
05 04 2024 09:22:18.496:INFO [launcher]: Starting browser Chrome
05 04 2024 09:22:48.500:WARN [launcher]: Chrome has not captured in 30000 ms, killing.
05 04 2024 09:22:48.752:INFO [launcher]: Trying to start Chrome again (1/2).
05 04 2024 09:23:18.753:WARN [launcher]: Chrome has not captured in 30000 ms, killing.
05 04 2024 09:23:19.066:INFO [launcher]: Trying to start Chrome again (2/2).
05 04 2024 09:23:27.957:INFO [Chrome 123.0.0.0 (Windows 10)]: Connected on socket 04VO4Msgesdtr4EPAAAB with id 55656365
debug preview-middleware Serving test route: /test/unitTests.qunit.html
05 04 2024 09:23:28.026:ERROR [karma-server]: UnhandledRejection: TypeError: res.status is not a function
    at FlpSandbox.<anonymous> (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:371:25)
    at Generator.next (<anonymous>)
    at fulfilled (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:5:58)
05 04 2024 09:23:28.026:ERROR [karma-server]: TypeError: res.status is not a function
    at FlpSandbox.<anonymous> (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:371:25)
    at Generator.next (<anonymous>)
    at fulfilled (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:5:58)
```

As documented in the [karma-ui5](https://www.npmjs.com/package/karma-ui5#notes-on-ui5-tooling-custom-server-middleware) plugin, the middleware must use the connect API (instead of express).

On the other side the connect API will not work outside the context of karma

```
Server started
URL: http://localhost:8080/
...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:266
                res.writeHead(200, { 'Content-Type': 'text/html' }).end(html);
                                                                   ^
TypeError: Cannot read properties of undefined (reading 'end')
    at FlpSandbox.<anonymous> (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:266:68)
    at Generator.next (<anonymous>)
    at fulfilled (...\node_modules\@sap-ux\preview-middleware\dist\base\flp.js:5:58)
```

So what would do the job is something like

```
try {
    //plain vanilla middleware usage
    res.status(200).contentType('html').send(html);
} catch (e) {
    //middleware executed by karma
    res.writeHead(200, { 'Content-Type': 'text/html' }).end(html);
}
```

### Expected results

usage of preview-middleware as part of a karma execution works

### Actual results

usage of preview-middleware as part of a karma execution fails

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
To be more compatible we should try to rely on the common APIs  in `connect` and `express`. We did a similar fix before (https://github.com/SAP/open-ux-tools/commit/bce98f84ebc36c4e779f709feaae2ff3ab0f0462).

**Comment by heimwege** [comment]
I'll have a look
