### ISSUE TITLE
BUG - Generated Freestyle TypesScript project fails `build`

### ISSUE THREAD

**Issue by devinea** [SAP/open-ux-tools#882]
### Related Feature
Feature request: _issue number_

### Description
A clear description of what the bug is.

### Steps to Reproduce
1.  `cd /packages/fiori-freestyle-writer`
2. `UX_DEBUG=true pnpm test`
3. `cd test/test-output/worklistTemplate/worklist_ts`
4. `npm i && npm run build`

### Expected results
build completes without error

### Actual results

````
> ui5 build --config=ui5.yaml --clean-dest --dest dist

info builder:builder Building project wrk1 not including dependencies...
info builder:builder 🛠  (1/1) Building project wrk1
info builder:builder application wrk1 🔨 (1/9) Running task escapeNonAsciiCharacters...
info builder:builder application wrk1 🔨 (2/9) Running task replaceCopyright...
info builder:builder application wrk1 🔨 (3/9) Running task replaceVersion...
info builder:builder application wrk1 🔨 (4/9) Running task ui5-tooling-transpile-task...
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/model/formatter.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/model/models.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/Object.controller.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/Worklist.controller.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/NotFound.controller.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/ErrorHandler.tse-task...
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/BaseController.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/controller/App.controller.ts
info builder:customtask:ui5-tooling-transpile Transpiling file /resources/wrk1/Component.ts
info builder:builder application wrk1 🔨 (5/9) Running task generateFlexChangesBundle...
info builder:builder application wrk1 🔨 (6/9) Running task generateComponentPreload...
ERR! lbt:analyzer:JSModuleAnalyzer Unhandled AST node type ChainExpression Node {
ERR! lbt:analyzer:JSModuleAnalyzer   type: 'ChainExpression',
ERR! lbt:analyzer:JSModuleAnalyzer   start: 1777,
ERR! lbt:analyzer:JSModuleAnalyzer   end: 1810,
ERR! lbt:analyzer:JSModuleAnalyzer   expression: Node {
ERR! lbt:analyzer:JSModuleAnalyzer     type: 'CallExpression',
ERR! lbt:analyzer:JSModuleAnalyzer     start: 1777,
ERR! lbt:analyzer:JSModuleAnalyzer     end: 1810,
ERR! lbt:analyzer:JSModuleAnalyzer     callee: Node {
ERR! lbt:analyzer:JSModuleAnalyzer       type: 'MemberExpression',
ERR! lbt:analyzer:JSModuleAnalyzer       start: 1777,
ERR! lbt:analyzer:JSModuleAnalyzer       end: 1808,
ERR! lbt:analyzer:JSModuleAnalyzer       object: [Node],
ERR! lbt:analyzer:JSModuleAnalyzer       property: [Node],
ERR! lbt:analyzer:JSModuleAnalyzer       computed: false,
ERR! lbt:analyzer:JSModuleAnalyzer       optional: true
ERR! lbt:analyzer:JSModuleAnalyzer     },
ERR! lbt:analyzer:JSModuleAnalyzer     arguments: [],
ERR! lbt:analyzer:JSModuleAnalyzer     optional: false
ERR! lbt:analyzer:JSModuleAnalyzer   }
ERR! lbt:analyzer:JSModuleAnalyzer }
ERR! lbt:resources:ResourcePool failed to analyze wrk1/controller/Object.controller.js: Error: Unhandled AST node type ChainExpression
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:506:12)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:498:7)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:478:7)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:406:7)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at JSModuleAnalyzer.analyze (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:290:3)
ERR! lbt:resources:ResourcePool     at determineDependencyInfo (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/resources/ResourcePool.js:76:16)
ERR! lbt:analyzer:JSModuleAnalyzer Unhandled AST node type ChainExpression Node {
ERR! lbt:analyzer:JSModuleAnalyzer   type: 'ChainExpression',
ERR! lbt:analyzer:JSModuleAnalyzer   start: 2525,
ERR! lbt:analyzer:JSModuleAnalyzer   end: 2580,
ERR! lbt:analyzer:JSModuleAnalyzer   expression: Node {
ERR! lbt:analyzer:JSModuleAnalyzer     type: 'CallExpression',
ERR! lbt:analyzer:JSModuleAnalyzer     start: 2525,
ERR! lbt:analyzer:JSModuleAnalyzer     end: 2580,
ERR! lbt:analyzer:JSModuleAnalyzer     callee: Node {
ERR! lbt:analyzer:JSModuleAnalyzer       type: 'MemberExpression',
ERR! lbt:analyzer:JSModuleAnalyzer       start: 2525,
ERR! lbt:analyzer:JSModuleAnalyzer       end: 2573,
ERR! lbt:analyzer:JSModuleAnalyzer       object: [Node],
ERR! lbt:analyzer:JSModuleAnalyzer       property: [Node],
ERR! lbt:analyzer:JSModuleAnalyzer       computed: false,
ERR! lbt:analyzer:JSModuleAnalyzer       optional: true
ERR! lbt:analyzer:JSModuleAnalyzer     },
ERR! lbt:analyzer:JSModuleAnalyzer     arguments: [ [Node] ],
ERR! lbt:analyzer:JSModuleAnalyzer     optional: false
ERR! lbt:analyzer:JSModuleAnalyzer   }
ERR! lbt:analyzer:JSModuleAnalyzer }
ERR! lbt:resources:ResourcePool failed to analyze wrk1/controller/Worklist.controller.js: Error: Unhandled AST node type ChainExpression
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:506:12)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:478:7)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:406:7)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at /open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:29
ERR! lbt:resources:ResourcePool     at Array.forEach (<anonymous>)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:370:10)
ERR! lbt:resources:ResourcePool     at visit (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:510:6)
ERR! lbt:resources:ResourcePool     at JSModuleAnalyzer.analyze (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/analyzer/JSModuleAnalyzer.js:290:3)
ERR! lbt:resources:ResourcePool     at determineDependencyInfo (/open-ux-tools/packages/fiori-freestyle-writer/test/test-output/worklistTemplate/worklist_ts/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/lbt/resources/ResourcePool.js:76:16)
WARN lbt:bundle:Builder **** warning: module wrk1/utils/locate-reuse-libs.js requires top level scope and can only be embedded as a string (requires 'eval')
info builder:builder application wrk1 🔨 (7/9) Running task createDebugFiles...
info builder:builder application wrk1 🔨 (8/9) Running task uglify...
info builder:builder application wrk1 🔨 (9/9) Running task generateVersionInfo...
info builder:builder Build succeeded in 705 ms
info builder:builder Executing cleanup tasks...
````

Related issue https://github.com/SAP/ui5-tooling/issues/575 

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by tobiasqueck** [comment]
Conditional chaining doesn't work so you need to separate check e.g. https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Object.controller.ts#L64 needs to be converted from `if (!elementBinding?.getBoundContext())` to  `if (!elementBinding || !elementBinding.getBoundContext())`

Same for https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Worklist.controller.ts#L87
